"""
dashboard/components/ai_synthesis.py — Module 6: AI Synthesis

Public API:
    render(row, ticker, sent_df) — renders the expander panel in app.py
"""

from __future__ import annotations

import hashlib

import pandas as pd
import streamlit as st


def _cache_key(row: pd.Series, ticker: str, sent_df: pd.DataFrame | None) -> str:
    from ai.prompt_template import build_user_message, system_prompt

    prompt = system_prompt() + "\n\n---USER---\n\n" + build_user_message(row, ticker, sent_df)
    digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
    return f"_ai_synthesis_{ticker.upper()}_{digest}"


def render(row: pd.Series, ticker: str, sent_df: pd.DataFrame | None) -> None:
    with st.expander("Module 6 — AI Synthesis", expanded=True):

        # Filter sentiment to this ticker — fall back to live fetch if not in cache
        ticker_sent: pd.DataFrame | None = None
        if sent_df is not None:
            mask = sent_df["ticker"].str.upper() == ticker.upper()
            filtered = sent_df[mask].sort_values("date").reset_index(drop=True)
            ticker_sent = filtered if not filtered.empty else None

        if ticker_sent is None:
            from sentiment.trend import load_ticker_sentiment
            live = load_ticker_sentiment(ticker)
            ticker_sent = live if not live.empty else None

        try:
            from ai.synthesize import synthesize
        except ImportError:
            st.info(
                "AI synthesis is not yet configured. "
                "Ensure `ai/synthesize.py` exists and `ANTHROPIC_API_KEY` is set."
            )
            return

        cache_key = _cache_key(row, ticker, ticker_sent)
        if st.button("Regenerate", key=f"_ai_regenerate_{ticker.upper()}"):
            st.session_state.pop(cache_key, None)

        with st.spinner("Generating AI synthesis…"):
            try:
                if cache_key not in st.session_state:
                    st.session_state[cache_key] = synthesize(row, ticker, ticker_sent)
                result = st.session_state[cache_key]
            except Exception as exc:
                st.error(f"AI synthesis failed: {exc}")
                return

        # Divergence alert (shown first if present)
        if result.get("divergence_flag"):
            st.warning(
                f"**Divergence detected:** {result.get('divergence_note', '')}",
                icon="⚠️",
            )

        col_bull, col_bear = st.columns(2)

        with col_bull:
            st.markdown("#### Bull Case")
            st.success(result["bull"])

        with col_bear:
            st.markdown("#### Bear Case")
            st.error(result["bear"])

        risks = result.get("risks", [])
        if risks:
            st.markdown("#### Key Risks")
            for risk in risks:
                st.markdown(f"- {risk}")

        fyearq = row.get("fyearq")
        quant_vintage = f"FY {int(fyearq)} Q4" if pd.notna(fyearq) else "Dec 2024"
        sent_vintage = ""
        if ticker_sent is not None and not ticker_sent.empty:
            latest_sent = ticker_sent.sort_values("date").iloc[-1]
            sent_label = latest_sent.get("quarter_label", "")
            sent_date = latest_sent.get("date")
            date_str = pd.to_datetime(sent_date).strftime("%b %Y") if pd.notna(sent_date) else ""
            sent_vintage = f" · Sentiment through {sent_label} ({date_str})" if date_str else f" · Sentiment through {sent_label}"
        st.caption(
            f"Generated by Claude (claude-sonnet-4-6) · "
            f"Quant data: Compustat {quant_vintage} · CRSP Dec 2024"
            f"{sent_vintage} · Not financial advice."
        )
