"""
dashboard/components/ai_synthesis.py — Module 6: AI Synthesis

Public API:
    render(row, ticker, sent_df) — renders the expander panel in app.py
"""

from __future__ import annotations

import pandas as pd
import streamlit as st


def render(row: pd.Series, ticker: str, sent_df: pd.DataFrame | None) -> None:
    with st.expander("Module 6 — AI Synthesis", expanded=True):

        # Filter sentiment to this ticker — fall back to live fetch if not in cache
        ticker_sent: pd.DataFrame | None = None
        if sent_df is not None:
            mask = sent_df["ticker"].str.upper() == ticker.upper()
            filtered = sent_df[mask].sort_values("date").reset_index(drop=True)
            ticker_sent = filtered if not filtered.empty else None

        if ticker_sent is None:
            from sentiment.trend import load_ticker_sentiment
            live = load_ticker_sentiment(ticker)
            ticker_sent = live if not live.empty else None

        with st.spinner("Generating AI synthesis…"):
            try:
                from ai.synthesize import synthesize
                result = synthesize(row, ticker, ticker_sent)
            except Exception as exc:
                st.error(f"AI synthesis failed: {exc}")
                return

        # Divergence alert (shown first if present)
        if result.get("divergence_flag"):
            st.warning(
                f"**Divergence detected:** {result.get('divergence_note', '')}",
                icon="⚠️",
            )

        col_bull, col_bear = st.columns(2)

        with col_bull:
            st.markdown("#### Bull Case")
            st.success(result["bull"])

        with col_bear:
            st.markdown("#### Bear Case")
            st.error(result["bear"])

        risks = result.get("risks", [])
        if risks:
            st.markdown("#### Key Risks")
            for risk in risks:
                st.markdown(f"- {risk}")

        st.caption(
            "Generated by Claude (claude-sonnet-4-6) from quant signals + earnings call sentiment. "
            "Not financial advice."
        )
